### ISSUE TITLE
Error setting target temperature 

### ISSUE THREAD

**Issue by twosh** [klejejs/ha-thermia-heat-pump-integration#46]
Hi!
I've used your component for quite some time, although it's basically the last couple of weeks when I've actually starting controlling the heat pump (Calibra) actively since I switched to spot price. :)

Today however, it stopped working to change the target temperature. I still receive updated data such as outside temperature, brine in/out temperature etc. Checking the logs I found the following:

`This error originated from a custom integration.

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia/water_heater.py:145 
Integration: Thermia Heat Pump (documentation, issues) 
First occurred: 6:26:01 PM (8 occurrences) 
Last logged: 7:41:03 PM

Error setting register 29422 value. 400`

Any chance you have any idea of what's going on? Has thermia changed their api or something? Grateful for your contributions and for any help regarding this! 🙏

Cheers!

**Comment by ebakoba** [comment]
I am experiencing the same issue on my Diplomat. I think the underlying problem might be in the `ThermiaOnlineAPI`. For some reason [this function](https://github.com/klejejs/python-thermia-online-api/blob/c266a7e96dd13708cecd907788dfdd07f92e5a3f/ThermiaOnlineAPI/api/ThermiaAPI.py#L431) is returning HTTP 400 error, which means `Bad Request`. 

I suspect that Thermia might have made changes to their API, because it seems to me that `registerIndex` on [this line](https://github.com/klejejs/python-thermia-online-api/blob/c266a7e96dd13708cecd907788dfdd07f92e5a3f/ThermiaOnlineAPI/api/ThermiaAPI.py#L443) has been renamed to `registerSpecificationId`. As can be seen from the screenshot of the network request made by the official API:

![image](https://user-images.githubusercontent.com/14753019/227000048-8381d8d2-bf83-490e-bb2e-1b3c7131c7d3.png)

**Comment by PalmSwe** [comment]
Same problem here when changing hot water or any heater setting. But still, get all heater data correctly.

"Error setting register 1070 value. 400".

**Comment by eljobo** [comment]
Same problem here.

**Comment by Sepulnation** [comment]
Same problem here.

**Comment by d-flower** [comment]
I have the same problem.

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia/switches/hot_water_switch.py:63
Integration: Thermia Heat Pump (documentation, issues)
First occurred: 12:00:00 (2 occurrences)
Last logged: 12:06:40

Error setting register 1059 value. 400

**Comment by klejejs** [comment]
Thank you all for reporting this! I will be looking into it ASAP.

**Comment by klejejs** [comment]
The new version `2.18` fixes the issue. Please update and report if there are still problems.

**Comment by PalmSwe** [comment]
Still have the same error after update.

Error setting register 1363 value. 400

**Comment by flexi80** [comment]
It now works to change the temperature setting, but not to turn on and off the water heater, however it displays the current setting. 

This error originated from a custom integration.

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia/switches/hot_water_switch.py:63 
Integration: Thermia Heat Pump (documentation, issues) 
First occurred: 06:42:38 (1 occurrences) 
Last logged: 06:42:38

Error setting register 1059 value. 400

**Comment by Sepulnation** [comment]
Exactly as flexi80 writes, it works to change the temperature setting, but not to change mode (AUTO, HOT_WATER, OFF......) of the water heater.

Thank you.
