### ISSUE TITLE
Thermia iTec missing Desired Supply Line Temperature

### ISSUE THREAD

**Issue by oskari** [klejejs/ha-thermia-heat-pump-integration#57]
`This entity is no longer being provided by the thermia integration. If the entity is no longer in use, delete it in settings.`

**Comment by klejejs** [comment]
This suggests that Thermia Online has removed that value and is returning nothing, which is why this is shown. Are you familiar with Python? Could you please follow [these instructions](https://github.com/klejejs/python-thermia-online-api#regarding-unsupported-models) and send me the debug file, so I can investigate further?

**Comment by oskari** [comment]
I updated to 3.2.0 and it seems to be showing again
