### ISSUE TITLE
When installation name changes integrations stop to work

### ISSUE THREAD

**Issue by janfryauf** [klejejs/ha-thermia-heat-pump-integration#99]
Hi,

I found out when my Installation name changed on the online website, HA sensors won't work anymore and the new ones are created with different name.

The main device entity id stays the same: water_heater.thermia (and name e.g. My Thermia)
But all other entities are named based on the installation name: switch.my_thermia_hot_water

So when the name change to e.g. Thermia iTec then all entities be like: switch.thermia_itec_hot_water

I guess the reason for this is that you can have many devices so it's depended on the installation name?
The thing is, my installation name was recently changed without my input - to smth like My Kundrata Thermia - and figured it's some Swedish word, no idea why that happend.

Maybe we could figure out how to name entities so they stay the same when name changes?

**Comment by klejejs** [comment]
Hey! Sorry to hear about your issue.
Unfortunately, as you say, the names need to be unique, so if a user has multiple heat pumps, each one has their own sensors based on it. As users usually do not change the name, and due to how Thermia updates the data, it is out of scope of this integration to have something like you requested.
